version: '3.8'
services:
  shipxplorer:
    image: ghcr.io/sdr-enthusiasts/shipxplorer
    container_name: shipxplorer
    hostname: shipxplorer
    restart: always
    environment:
      - SHARING_KEY=
      - SERIAL_NUMBER=
      - RTLSDR_DEVICE_SERIAL=device_serial
      - VERBOSE_LOGS=true
      - UDP_FEEDS=
      - RTLSDR_DEVICE_GAIN=
      - SXFEEDER_EXTRA_OPTIONS=
      - AISCATCHER_EXTRA_OPTIONS=
#    ports:
    devices:
      - /dev/bus/usb
    tmpfs:
      - /tmp
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      # - /opt/shipxplorer/cpuinfo/cpuinfo:/proc/cpuinfo # only for x86 systems - see README.md
